# Generated by Django 3.0 on 2020-08-03 03:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200802_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
