# Generated by Django 3.0 on 2020-08-03 04:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
        ),
    ]
