# Generated by Django 3.0.9 on 2020-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200803_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='a slug to identify posts by this category', max_length=250, verbose_name='slug'),
        ),
    ]
