# Generated by Django 3.0 on 2020-07-27 02:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0007_blogpageauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpageauthor',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='website',
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPage'),
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='blog.BlogPage'),
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Post Authors',
            },
        ),
    ]
