# Generated by Django 3.0 on 2020-07-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200727_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpageauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogAuthor'),
        ),
    ]
