# Generated by Django 3.0 on 2020-08-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200803_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogabout',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='blogabout',
            name='latlng_address',
        ),
    ]
