# Generated by Django 3.0 on 2020-07-28 01:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogabout',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add your text', required=True))]))], blank=True, null=True),
        ),
    ]
