# Generated by Django 3.0 on 2020-07-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='facebook url', null=True)),
                ('gmail', models.URLField(blank=True, help_text='gmail url', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='linkedin url', null=True)),
                ('github', models.URLField(blank=True, help_text='github url', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
